### ISSUE TITLE
Error on displayed license

### ISSUE THREAD

**Issue by rsertelon** [vbauer/android-arsenal.com#197]
Hi,

On this project: https://android-arsenal.com/details/1/1930 the license stated is LGPLv3, but the actual license of the project is GPLv3

There might be a bug in the discovery of the license.

**Comment by vbauer** [comment]
Thank you for found mistake, I've just fixed it.

PS: You can also update this information as author of this project (just login on site via Github, open details page, and press on "Edit" link).

**Comment by rsertelon** [comment]
Ah ok, didn't know, thanks. I thought it was automatically done :)

**Comment by vbauer** [comment]
No problem. :) Actually, we tried to implement some heuristic algorithm to detect information about license, but results had a lot of mistakes. Maybe this feature will be improved and added in future.

**Comment by rsertelon** [comment]
Maybe you could use the LICENSE file that is present, and compare its hash to well-known licenses ;)

**Comment by vbauer** [comment]
Yes, it was just a part of algorithm and even with this file we have a lot of problems, because developers call it in different styles, ex: "LICENSE", "License", "LICENSE.md", "License.md", "LICENSE.txt", "Licenses.txt", etc... so we have to make a lot of requests to Github and it is not great ("request limit" will cut requests).

**Comment by rsertelon** [comment]
It's sad that github does not provide this information as repository metadata...

Anyways, nice website!
