### ISSUE TITLE
Android Client

### ISSUE THREAD

**Issue by aashrairavooru** [vbauer/android-arsenal.com#204]
I am planning to work on an open source android client for this site, if you can expose the projects as an api with gcm support for updates on new projects we can build something awesome.

**Comment by vbauer** [comment]
Thank you, but I'm not sure that mobile application will provide some meaning benefits:

* A very simple wrapper-application for Android Arsenal site is available on Google Play: https://play.google.com/store/apps/details?id=com.android_arsenal.androidarsenal
* Web design of the site is responsive, so it should work fine on mobile devices.
* News about projects could be read via Pushbullet, Reddit, Google+, Twitter, Facebook, and RSS.
* A lot of Android developers use the site via desktop computers or laptops (~95%).

I've already received a lot of suggestions to make application for Android and I'm glad to know that people want to help Android Arsenal, but due to the reasons listed above, I believe that it isn't so necessary. :) If mobile application is really needed in the future, I can contact you.

**Comment by aashrairavooru** [comment]
Hmm sound reasonable I guess, if there are plans will be happy to help

**Comment by vbauer** [comment]
Thank you for suggestion!

**Comment by aashrairavooru** [comment]
One interesting thing that we can do with an android client is letting developers of open source projects upload demo apks in their github account, and give an option of installing them directly through the app maybe then others can get a better and faster understanding of the project rather than going through the long process of git cloning the project and then compiling the given sample into their device because not all developers upload their sample apps to the play store

**Comment by vbauer** [comment]
Yes, but I'm still thinking about this idea. At the current moment, authors could only add online emulator via Appetize.io service, ex: http://android-arsenal.com/details/1/741 (see "Demo" tab) Probably, I'll remove integration with this service and allow to upload APK files on the site (or something similar).

**Comment by aashrairavooru** [comment]
Or just ask the developer to add apks under a folder in their repo and we
can just download them directly as a raw content from github
